name = "isbgpsafeyet"
main = "workers-site/index.js"
account_id = "04cb62d57d02b212c133288d8e42f84c"
compatibility_date = "2023-04-13"
send_metrics = false
node_compat = true  # ...needed for Buffer.
workers_dev = false
rules = [{ type = "Text", globs = ["**/*.csv"], fallthrough = true }]
vars = { ENVIRONMENT = "dev" }

[site]
bucket = "./public"

[env.production]
workers_dev = false
vars = { ENVIRONMENT = "production" }
routes = [{ pattern = "isbgpsafeyet.com/*", zone_id = "72a2ccd3f2b1c26c23d134d8d1a70a5d" }]
